### ISSUE TITLE
Ok to archive?

### ISSUE THREAD

**Issue by marcoscaceres** [drufball/async-append#7]
This repo hasn't had much activity for a long time... would it be ok to archive this?

**Comment by chrishtr** [comment]
I think so yes. The repo that supersedes this effort is https://github.com/WICG/display-locking.

If it's archived I assume the issues are still visible etc right?

**Comment by marcoscaceres** [comment]
Yes, issues remain visible but locked. Do you want to transfer some of them to display-locking?

**Comment by chrishtr** [comment]
> Do you want to transfer some of them to display-locking?

I reviewed the existing issues, and don't need to migrate any. Thanks for asking.
